spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://wang9ri-db.duckdns.org:25432/playground
    username: playground
    password: qwe123
  jpa:
    open-in-view: false

#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#        use_sql_comments: true
#    show-sql: true
