spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/playground
    username: playground
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

    open-in-view: false


logging:
  level:
    org.hibernate.sql: debug