spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://wang9ri-db.duckdns.org:25432/playground
    #    url: jdbc:postgresql://129.154.219.240:25432/playground
    username: playground
    password: qwe123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: dev
    open-in-view: false
    show-sql: true



logging:
  level:
    org.hibernate.sql: debug